language: node_js
node_js: 8
os:
  - linux
env:
  global:
    - secure: "EuQQSD9GKeAUtFhNGe/m23IYXKVTr8CPl9f7O/PsVDkDMsO6E15o16hn9rn/kIeMEE9+UsCGapFJYlTg+jvZncr8kNTWkKTxsaYS9ejc9br4ePzJmg4LXrelIsunkUGTRBG7wd5I7g+Tx24k02EItftYhzhw3GV3sDvw7VISts3CaCFrGMwOlI4vuhFxJ7N9XRg3HFPY4O9847R/nfhbN9eMqI1kg9xA2INoYaeqxxjWjCX/YlRNpUjkpauv3Owc9Z+B5DYSAlywTModqiUdkiAGmFptydo8gkCqll+iuFfZAV7KT338gVVP3XLNVP1Bq7ZrcqPimhepStX1smEo7vtPzUSb4Wiy03hXlkhDEhLzOf629bGrwpMDy49oAYN0+7o2JBmtV91VEOOs2+ziDTprdv3l4VyX9em+/tf3KxZqTNuiq2Rbl2607zQ3MVYzvHqedoAJiimzUAqMEC4JZmAhlS4dnLFpG2aZv0vuNS9hzVcmSrwcUUwQXWDuRVJkI2mpvL/avbSSH2+kww+I2Uz6VPIOnWoMlY+PJ1i7nMGLpbRY9D4QY1JGJh897hSTHw3F21/4h7kSrkPG0rIdCTCiJ3sXBfUdeSdBi0E+ca9vUWZBbsfH0NdRcw4n0cYiG0NaV1zNA6EIRi8L1GHLtPtYbu/Gm2HM63d7agIQvR0="
  matrix:
    # This is obviously not ideal. I never was good with linear algebra. Damn matrixes.
    # -- It looks like this kind of dumb explictness is a known issue for travis, and
    # is low on their priority list.
    # Note: CCX vs. CXX? WTF FTW.
    - CCX=gcc-4.8 FULL_CHECK=false # osx
    - CCX=gcc-4.8 FULL_CHECK=true # osx
    - CXX=g++-4.8 FULL_CHECK=false # linux
    - CXX=g++-4.8 FULL_CHECK=true # linux
cache:
  directories:
    - "node_modules"
matrix:
  # Don't build for incompatible c compilers.
  exclude:
    - os: osx
      env: CXX=g++-4.8 FULL_CHECK=false
    - os: osx
      env: CXX=g++-4.8 FULL_CHECK=true
    - os: linux
      env: CCX=gcc-4.8 FULL_CHECK=false
    - os: linux
      env: CCX=gcc-4.8 FULL_CHECK=true
# before_install:
before_script:
  # `npm install` is automatic
  - npm install -g node-gyp license-checker
  - npm install -g codecov
  - npm run getemerald
script:
  # Install Janus
  - curl -sL https://raw.githubusercontent.com/ethereumproject/janus/master/get.sh | bash
  - export PATH=$PATH:$PWD/janusbin
  - export APP_VERSION_GIT_TAG="$(janus version -format 'TAG_OR_NIGHTLY')"
  - echo "Building app version $APP_VERSION_GIT_TAG"
  - if [[ $(license-checker --production --exclude '(GPL-2.0 OR MIT)' | grep GPL) ]]; then license-checker --production | grep -C 1 GPL && false; fi
  - npm run build
  - npm run test:coverage
  - if [[ $FULL_CHECK == "true" ]]; then npm run lint --silent; fi
  - if [[ $FULL_CHECK == "true" ]]; then npm run flow --silent; fi
  # Don't build releases for lint tests.
  # Env var disables build signing.
  - if [[ "$FULL_CHECK" == "false" ]]; then env CSC_IDENTITY_AUTO_DISCOVERY=false npm run dist; fi
after_success:
  # Show dist directory contents after a successful build.
  - if [[ "$FULL_CHECK" == "false" ]]; then ls -l ./dist/; fi
before_deploy:
  # Set up GCP
  - openssl aes-256-cbc -k "$GCP_PASSWD" -in gcloud-travis.json.enc -out .gcloud.json -d
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - build-essential
    - libudev-dev
    - libusb-1.0-0
    - libusb-1.0-0-dev
    # - gcc-multilib
    # - g++-multilib
    # - gcc-4.8-multilib
    # - g++-4.8-multilib
    # - ia32-libs
    # - libc6-dev #predefs
deploy:
  - provider: script
    script: ./gcloud-deploy.sh
    skip_cleanup: true
    on:
      branch: master

  - provider: script
    script: ./gcloud-deploy.sh
    skip_cleanup: true
    on:
      tags: true
