os: Visual Studio 2015
environment:
  GCP_PASSWD:
    secure: EYln0RTOPClcGR+ek/bjNwoi7AQ8uuNl5CSTjr/oqKlpoFk3iJdYDxYHMBAiY9cCG+MxvmnM5U+hDD8VvuS2S0fX90tVarWg9CX0e3Imm2w=
install:
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin\;%PATH%
  # Install janus.
  - curl -sL https://raw.githubusercontent.com/ethereumproject/janus/master/get-windows.sh | bash
  - set PATH=./janusbin;%PATH%
  # Set up version from git tags.
  - ps: $env:VERSION_BASE = "$(janus.exe version -format='v%M.%m.x')"
  - ps: $env:VERSION = "$(janus.exe version -format='v%M.%m.%C-%S')"
  # expected by Electron Builder config
  - ps: $env:APP_VERSION_GIT_TAG="$(janus version -format 'TAG_OR_NIGHTLY')"
  - echo %VERSION_BASE% %VERSION%
  # Set up build dependencies.
  - ps: Install-Product node 8 x64
  - set CI=true
  - npm install -g npm@latest windows-build-tools@1.3.2 node-gyp
  - ps: $env:Path += ";$env:USERPROFILE\.windows-build-tools\python27"
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
  - npm run getemerald
build: off
version: '{build}'
test_script:
  # CSC...=false env var disables app signing for osx, can't hurt to have it here too.
  # But probably useless, since the dist script build for _current_ operating system.
  - npm run dist
#artifacts:
#  - path: './dist/*.exe'
#    name: emerald-wallet
before_deploy:
  # Set up GCP upload.
  #- nuget install secure-file -ExcludeVersion
  #- secure-file\tools\secure-file -decrypt gcloud-appveyor.json.enc -secret %GCP_PASSWD% -out .gcloud.json
deploy_script:
  - ps: >-
      If (($env:APPVEYOR_REPO_BRANCH -eq 'master') -or ($env:APPVEYOR_REPO_TAG -eq 'true')) {
          echo "Deploy to http://builds.etcdevteam.com/emerald-wallet/$env:VERSION_BASE/"
          janus.exe deploy -to="builds.etcdevteam.com/emerald-wallet/$env:VERSION_BASE/" -files="./dist/*.exe" -key="./gcloud-appveyor.json.enc"
      }
